"""schema inicial

Revision ID: 0001_inicial
Revises: 
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001_inicial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('escritorio_id', sa.UUID(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('acao', sa.Text(), nullable=False),
    sa.Column('recurso', sa.Text(), nullable=True),
    sa.Column('detalhe', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escritorio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificado',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('escritorio_id', sa.UUID(), nullable=False),
    sa.Column('cnpj_raiz', sa.String(length=8), nullable=False),
    sa.Column('pfx_ciphered', sa.LargeBinary(), nullable=False),
    sa.Column('senha_ciphered', sa.LargeBinary(), nullable=False),
    sa.Column('titular_cnpj', sa.String(length=14), nullable=True),
    sa.Column('titular_nome', sa.Text(), nullable=True),
    sa.Column('valido_de', sa.Date(), nullable=True),
    sa.Column('valido_ate', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['escritorio_id'], ['escritorio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('escritorio_id', 'cnpj_raiz', 'titular_cnpj')
    )
    op.create_index('ix_certificado_validade', 'certificado', ['valido_ate'], unique=False)
    op.create_table('empresa',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('escritorio_id', sa.UUID(), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('cnpj_raiz', sa.String(length=8), nullable=False),
    sa.Column('razao_social', sa.Text(), nullable=False),
    sa.Column('inscricao_municipal', sa.Text(), nullable=True),
    sa.Column('municipio_ibge', sa.String(length=7), nullable=True),
    sa.Column('regime_tributario', sa.Text(), nullable=True),
    sa.Column('ultimo_nsu', sa.BigInteger(), nullable=False),
    sa.Column('sync_ativo', sa.Boolean(), nullable=False),
    sa.Column('ultimo_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultimo_sync_status', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['escritorio_id'], ['escritorio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('escritorio_id', 'cnpj')
    )
    op.create_index(op.f('ix_empresa_cnpj_raiz'), 'empresa', ['cnpj_raiz'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('escritorio_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('senha_hash', sa.Text(), nullable=False),
    sa.Column('papel', sa.Text(), nullable=False),
    sa.Column('mfa_secret', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.CheckConstraint("papel in ('admin','operador','leitura')", name='ck_usuario_papel'),
    sa.ForeignKeyConstraint(['escritorio_id'], ['escritorio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('dfe_bruto',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('escritorio_id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('nsu', sa.BigInteger(), nullable=False),
    sa.Column('tipo_documento', sa.Text(), nullable=True),
    sa.Column('chave_acesso', sa.String(length=50), nullable=True),
    sa.Column('xml_path', sa.Text(), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('versao_layout', sa.Text(), nullable=True),
    sa.Column('recebido_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('tentativas_parse', sa.Integer(), nullable=False),
    sa.Column('erro_parse', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['escritorio_id'], ['escritorio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'nsu')
    )
    op.create_index(op.f('ix_dfe_bruto_chave_acesso'), 'dfe_bruto', ['chave_acesso'], unique=False)
    op.create_table('relatorio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('escritorio_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Text(), nullable=True),
    sa.Column('periodo_inicio', sa.Date(), nullable=True),
    sa.Column('periodo_fim', sa.Date(), nullable=True),
    sa.Column('formato', sa.Text(), nullable=True),
    sa.Column('filtros', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('arquivo_path', sa.Text(), nullable=True),
    sa.Column('solicitado_por', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['escritorio_id'], ['escritorio.id'], ),
    sa.ForeignKeyConstraint(['solicitado_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nfse',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('escritorio_id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('chave_acesso', sa.String(length=50), nullable=False),
    sa.Column('numero', sa.Text(), nullable=True),
    sa.Column('data_geracao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('competencia', sa.Date(), nullable=True),
    sa.Column('papel', sa.Text(), nullable=False),
    sa.Column('prestador_cnpj', sa.String(length=14), nullable=True),
    sa.Column('prestador_nome', sa.Text(), nullable=True),
    sa.Column('prestador_im', sa.Text(), nullable=True),
    sa.Column('tomador_cnpj', sa.String(length=14), nullable=True),
    sa.Column('tomador_nome', sa.Text(), nullable=True),
    sa.Column('tomador_im', sa.Text(), nullable=True),
    sa.Column('municipio_incidencia', sa.String(length=7), nullable=True),
    sa.Column('valor_servico', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('desconto_incondicionado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('base_calculo', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('aliquota_issqn', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('valor_issqn', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('issqn_retido', sa.Boolean(), nullable=True),
    sa.Column('tributacao_issqn', sa.Text(), nullable=True),
    sa.Column('simples_nacional', sa.Boolean(), nullable=True),
    sa.Column('cod_tributacao_nacional', sa.Text(), nullable=True),
    sa.Column('item_nbs', sa.Text(), nullable=True),
    sa.Column('descricao_servico', sa.Text(), nullable=True),
    sa.Column('cst_ibs_cbs', sa.Text(), nullable=True),
    sa.Column('class_trib_ibs_cbs', sa.Text(), nullable=True),
    sa.Column('indicador_operacao', sa.Text(), nullable=True),
    sa.Column('bc_ibs_cbs', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('reemb_repasse', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('aliq_cbs', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('red_aliq_cbs', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('aliq_efetiva_cbs', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('valor_cbs', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('aliq_ibs_estadual', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('red_aliq_ibs_estadual', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('aliq_efetiva_ibs_estadual', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('valor_ibs_estadual', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('aliq_ibs_municipal', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('red_aliq_ibs_municipal', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('aliq_efetiva_ibs_municipal', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('valor_ibs_municipal', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_ibs_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('sit_trib_pis_cofins', sa.Text(), nullable=True),
    sa.Column('bc_pis_cofins', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('pis_aliquota', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('pis_debito', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cofins_aliquota', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('cofins_debito', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('descr_contrib_sociais', sa.Text(), nullable=True),
    sa.Column('irrf', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('contrib_sociais_retidas', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('contrib_previd_retida', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('pct_total_tributos_sn', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('informacoes_complementares', sa.Text(), nullable=True),
    sa.Column('situacao', sa.Text(), nullable=False),
    sa.Column('dfe_bruto_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("papel in ('prestador','tomador')", name='ck_nfse_papel'),
    sa.ForeignKeyConstraint(['dfe_bruto_id'], ['dfe_bruto.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['escritorio_id'], ['escritorio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'chave_acesso')
    )
    op.create_index('ix_nfse_competencia', 'nfse', ['empresa_id', 'competencia'], unique=False)
    op.create_index('ix_nfse_data_geracao', 'nfse', ['empresa_id', 'data_geracao'], unique=False)
    op.create_index('ix_nfse_prestador', 'nfse', ['prestador_cnpj'], unique=False)
    op.create_table('nfse_evento',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('escritorio_id', sa.UUID(), nullable=False),
    sa.Column('nfse_id', sa.BigInteger(), nullable=False),
    sa.Column('tipo_evento', sa.Text(), nullable=False),
    sa.Column('autor', sa.Text(), nullable=True),
    sa.Column('data_evento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_registro', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('xml_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['escritorio_id'], ['escritorio.id'], ),
    sa.ForeignKeyConstraint(['nfse_id'], ['nfse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nfse_id', 'tipo_evento', 'data_evento')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nfse_evento')
    op.drop_index('ix_nfse_prestador', table_name='nfse')
    op.drop_index('ix_nfse_data_geracao', table_name='nfse')
    op.drop_index('ix_nfse_competencia', table_name='nfse')
    op.drop_table('nfse')
    op.drop_table('relatorio')
    op.drop_index(op.f('ix_dfe_bruto_chave_acesso'), table_name='dfe_bruto')
    op.drop_table('dfe_bruto')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_empresa_cnpj_raiz'), table_name='empresa')
    op.drop_table('empresa')
    op.drop_index('ix_certificado_validade', table_name='certificado')
    op.drop_table('certificado')
    op.drop_table('escritorio')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
